name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # --- ESTE ES EL PASO QUE FALTABA ---
      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # Mantenemos el base-href para que los assets carguen bien en GitHub Pages
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web