name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Se activa al hacer push a la rama que veo en tu foto

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Web
        # Importante: El base-href permite que las rutas funcionen en GitHub Pages
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web